### PR TITLE
set indent size to 4 spaces

### PR DESCRIPTION
**Pull request by nosami**

### CODE REVIEW

**Comment by knocte** [comment]
Wow, this is going to destroy a lot of version-control history (aka git-blame). Is this really worth it?

If anything, I would recommend to create a script that can do this automatically over all files, and run it through all git history (this would require rewriting history, which has other downsides).

**Comment by nosami** [comment]
@knocte - If you wish to contribute such a script, I will use it :)

It's certainly worth it. Currently the source is a mixture of 2 spaces, 4 spaces and even 3 spaces (even within the same file).

**Comment by knocte** [comment]
In MS they have code for this kind of things (which I'm sure could be reused to be used in a script), i.e. the CodeFormatter tool was recently released as opensource IIRC, which formats C# and is used internally by them. So maybe you can poke someone to get the F# alternative?

**Comment by knocte** [comment]
Anyway, how did you create this diff? manually? I hope not :) If you didn't do it manually but through the MD code formatter, then you could automate it somehow in a script ;)

**Comment by nosami** [comment]
I tried Fantomas, but it didn't work, so I did it manually. It wasn't that much work

**Comment by knocte** [comment]
> I tried Fantomas, but it didn't work

You should have tried https://github.com/tpetricek/FSharp.Formatting

**Comment by 7sharp9** [comment]
Nope, that doesn't do any formatting!

**Comment by knocte** [comment]
> Nope, that doesn't do any formatting!

What? I completely thought it did, especially by reading this part of its README: 

```
Who Uses F# Formatting? The library is used by a number of F# projects. Most prominently, the F# snippets web site uses it to format snippets shared by the F# community.
```

**Comment by 7sharp9** [comment]
Its used for literal formatting of scripts mainly mainly markdown to html or fsx to html.

**Pull request merged**
